repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: flake8
      additional_dependencies: [
        "flake8-bugbear~=19.8",
        "flake8-import-order~=0.18",
        "flake8-tidy-imports~=2.0",
        "flake8-todo~=0.7",
        "flake8-string-format~=0.2",
      ]